version: "3.6"
services:
  nuxt-app:
    ports:
      - "3000:3000"
      - "24678:24678"
    build:
      dockerfile: Dockerfile
      context: ./config/nuxt-app
    working_dir: /var/www/html/nuxt-app
    user: node
    volumes:
      - ./nuxt-app:/var/www/html/nuxt-app
    command: sh -c "npm i && npm run dev"
    stdin_open: true
    tty: true
    networks:
      - default
